name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Config
        run: |
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}

      - name: Build
        run: |
          echo building app...
          npm install
          npm install -g @angular/cli
          ng build

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo deploying app...
          npx angular-cli-ghpages --dir=dist/ticerapps-v2 --no-silent

      - name: Tests
        run: |
          echo running tests...
          sudo apt install chromium-browser
          export CHROME_BIN=/usr/bin/chromium-browser
          npm run test
