name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          echo building app...
          npm install
          npm install -g @angular/cli
          ng build --configuration=production --base-href "/"

      - name: Deploy
        if: github.event.pull_request.merged == true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo deploying app...
          npx angular-cli-ghpages --dir=dist/ticerapps-v2 --no-silent

      - name: Tests
        if: github.event.pull_request.merged == true
        run: npm run test
